name: Web
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  web-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'npm'
        cache-dependency-path: web/package-lock.json
    - name: npm ci, build and test
      env:
        # CI set to true by default which results in warnings being treated as errors
        CI: false
      run: |
        npm ci
        npm test -- --coverage --watchAll=false
    - name: Upload coverage file
      uses: "actions/upload-artifact@v2"
      # skip locally in ACT
      if: ${{ !env.ACT }}
      with:
        name: "${{ github.job }}.coverage"
        path: |
          web/coverage/
        retention-days: 1